const LIMIT_PAGINATION_POST = 10;
const LIMIT_PAGINATION_REPLY = 10;
const LIMIT_PAGINATION_SUGGESTION = 10;
export {
  LIMIT_PAGINATION_POST,
  LIMIT_PAGINATION_REPLY,
  LIMIT_PAGINATION_SUGGESTION,
};
